HTMLへの埋め込みの課題
ogataka55/php_exercise01 pull request #7
Opened 2022-03-01 19:40 UTC by ogataka55

確認お願い致します。

2022-03-01 19:49 UTC, ogataka55 commented on 07/form2_3.php
> +    if ($score && $score < 60) {
ここのif文の中に「$score &&」を入れないと上手く動作しません…
(挿入せずに未入力または0で送信すると、エラーメッセージではなく「不合格です」ページに遷移)
色々自分なりに調査しましたが原因不明のままです。
可能であればご指南頂きたく:pray:

2022-03-01 22:01 UTC, kazu-taka requested changes
@ogataka55 
コメントしたので確認お願いします😊

2022-03-02 00:48 UTC, narusesuzuki commented on 07/form2_3.php
> +    if ($score && $score < 60) {
0の挙動は難しいですね😅
以下のような違いですね💦

```php
// $score < 60 は true
// $score は false 
// ともにtrueじゃないので処理されない
if ($score && $score < 60) { 
    header("Location: judge_ment.php?judge_ment={$ng_msg}");
    exit;
}
```

```php
// $score < 60 は trueなので処理される
if ($score < 60) {
    header("Location: judge_ment.php?judge_ment={$ng_msg}");
    exit;
}
```

2022-03-02 04:31 UTC, ogataka55 commented on 07/form2_3.php
> +    if ($score && $score < 60) {
確認有難うございます！

自分の認識では、「0」ないしは「未入力」は空になるから$score < 60だけでもひっかからずに問題ないという認識だったんですけど何か考え方が間違ってる感じですかね:sweat_smile:？

2022-03-02 05:04 UTC, ogataka55 commented on 07/form2_3.php
> +    if ($score && $score < 60) {
なるほどですねー
なかなかドツボに嵌りそうな内容ですね…笑
有難うございます:pray:

2022-03-02 05:04 UTC, merged